# Generated by Django 2.2.3 on 2022-11-03 10:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filetitle', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='Img/')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('choicesgender', models.CharField(max_length=50)),
                ('choicesmonth', models.CharField(max_length=50)),
                ('choicesday', models.CharField(max_length=50)),
                ('choicesyear', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('confirmation', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('choiceslanguage', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('choicesgender', models.CharField(max_length=50)),
                ('choicesmonth', models.CharField(max_length=50)),
                ('choicesday', models.CharField(max_length=50)),
                ('choicesyear', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('confirmation', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('choiceslanguage', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foldername', models.CharField(max_length=50)),
                ('folderdesc', models.CharField(max_length=255)),
                ('folderuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filetitle', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='files')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Folder')),
            ],
        ),
    ]
