# Generated by Django 2.2.3 on 2022-11-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221103_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='usr',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
